services:
  - type: web
    name: quarkus-projetoteste-jvm
    env: docker
    plan: free
    buildCommand: ./mvnw package
    dockerfilePath: src/main/docker/Dockerfile.jvm
    envVars:
      - key: DB_USERNAME
        fromDatabase:
          name: a_simple_project
          property: connectionString
      - key: DB_PASSWORD
        fromDatabase:
          name: a_simple_project
          property: connectionString
      - key: DB_URL
        fromDatabase:
          name: a_simple_project
          property: connectionString